# Generated by Django 5.1.1 on 2024-10-24 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_visitor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
